Allow percents when using decodeURIComponent for encoded HTML support
wp-shortcake/shortcake pull request #644
Opened 2016-10-03 05:43 UTC by sc0ttkclark

Fixes #634

Support percent characters in values that get encoded, otherwise JS errors like `Uncaught URIError: URI malformed(…)` happen and stop the shortcode embedding process.

2016-10-03 15:20 UTC, goldenapples requested changes
I don't know why I've never come across this bug - must have been sheer luck, I guess.

Thanks for troubleshooting this and finding a fix. The only problem here is the missing closing paren in the src file - can you fix that, and I'll merge this?

2016-10-03 15:20 UTC, goldenapples commented on js/src/models/shortcode.js
> +				attr.set( 'value', encodeURIComponent( decodeURIComponent( attr.get( 'value' ).replace( "%", "&#37;" ) ), { silent: true } );
This line is missing a closing parenthesis.

2016-10-03 15:25 UTC, sc0ttkclark commented on js/src/models/shortcode.js
> +				attr.set( 'value', encodeURIComponent( decodeURIComponent( attr.get( 'value' ).replace( "%", "&#37;" ) ), { silent: true } );
Fixed :)

2016-10-03 15:47 UTC, goldenapples approved these changes

2016-10-03 15:48 UTC, goldenapples commented
Thanks @sc0ttkclark and @kosmiq, merging this and will include the fix for version 0.7.0.

2016-10-03 15:48 UTC, merged

2017-04-18 17:44 UTC, cooms13 commented
Thanks everybody!